name: Daily Web Scraper

on:
  schedule:
    - cron: '0 9 * * *' # Runs every day at 9:00 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests reportlab google-genai

      - name: Run Scraper and Send Directly to WhatsApp
        env:
          MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          WHATSAPP_INSTANCE: ${{ secrets.WHATSAPP_INSTANCE }}
          WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
          MI_TELEFONO: ${{ secrets.MI_TELEFONO }}
        # Al correr el script, este genera el PDF en el disco temporal y lo despacha de inmediato
        run: python scraper_test.py

